# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudbuildgraph < Formula
  desc "Visualize your Google Cloud Build pipeline"
  homepage "https://github.com/patrickhoefler/cloudbuildgraph"
  version "0.6.8"

  depends_on "graphviz"

  on_macos do
    url "https://github.com/patrickhoefler/cloudbuildgraph/releases/download/v0.6.8/cloudbuildgraph_0.6.8_darwin_amd64.tar.gz"
    sha256 "971ac2edf5098c8f47eea75a49ac781b488837ea2273af9ca72df1bb5a672cc6"

    def install
      bin.install "cloudbuildgraph"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudbuildgraph
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/patrickhoefler/cloudbuildgraph/releases/download/v0.6.8/cloudbuildgraph_0.6.8_linux_amd64.tar.gz"
      sha256 "387f3ce7b4602496fa91febcc7343f52e10da578da7b4f4a8749f2ec1496c789"

      def install
        bin.install "cloudbuildgraph"
      end
    end
  end
end
