# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudbuildgraph < Formula
  desc "Visualize your Google Cloud Build pipeline"
  homepage "https://github.com/patrickhoefler/cloudbuildgraph"
  version "0.6.9"

  depends_on "graphviz"

  on_macos do
    url "https://github.com/patrickhoefler/cloudbuildgraph/releases/download/v0.6.9/cloudbuildgraph_0.6.9_darwin_amd64.tar.gz"
    sha256 "f843c470d0b12d0be8d55e7d06ab1d8f8ef8193d1cda94bc8b7d08e19d7ad813"

    def install
      bin.install "cloudbuildgraph"
    end

    on_arm do
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Cloudbuildgraph
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/patrickhoefler/cloudbuildgraph/releases/download/v0.6.9/cloudbuildgraph_0.6.9_linux_amd64.tar.gz"
        sha256 "b1e448207e59a366770aae5daa3ea9d03f3398984b3720175f8421c109dcd71e"

        def install
          bin.install "cloudbuildgraph"
        end
      end
    end
  end
end
