# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockerfilegraph < Formula
  desc "Visualize your multi-stage Dockerfile"
  homepage "https://github.com/patrickhoefler/dockerfilegraph"
  version "0.5.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/patrickhoefler/dockerfilegraph/releases/download/v0.5.0/dockerfilegraph_0.5.0_darwin_amd64.tar.gz"
    sha256 "61ddf7d53c44704eb4428223dc11bd1d8a692f2cf5d5afad7f7f5f12f7ddede3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/patrickhoefler/dockerfilegraph/releases/download/v0.5.0/dockerfilegraph_0.5.0_linux_amd64.tar.gz"
    sha256 "578aea6e4639eac9a97cd1da0be6b173e38033cdad0bd625ff9f305e219c0d67"
  end

  depends_on "graphviz"

  def install
    bin.install "dockerfilegraph"
  end
end
