# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockerfilegraph < Formula
  desc "Visualize your multi-stage Dockerfile"
  homepage "https://github.com/patrickhoefler/dockerfilegraph"
  version "0.4.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/patrickhoefler/dockerfilegraph/releases/download/v0.4.0/dockerfilegraph_0.4.0_darwin_amd64.tar.gz"
    sha256 "70e0dce6374450e93b9470199f366d49231c3d0799c01261baa6d4bfdb1a14af"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/patrickhoefler/dockerfilegraph/releases/download/v0.4.0/dockerfilegraph_0.4.0_linux_amd64.tar.gz"
    sha256 "acc69e7ffd620f467758bdffe157483034a038844a0ce5c6d08ee39c61ee6725"
  end

  depends_on "graphviz"

  def install
    bin.install "dockerfilegraph"
  end
end
