# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghtop < Formula
  desc "Get information about the most starred GitHub repos"
  homepage "https://github.com/patrickhoefler/ghtop"
  version "0.1.11"

  on_macos do
    url "https://github.com/patrickhoefler/ghtop/releases/download/v0.1.11/ghtop_0.1.11_darwin_amd64.tar.gz"
    sha256 "b1395916cac0f3818a27f49db24e086d772499c27e0d92352cfff926daab87b2"

    def install
      bin.install "ghtop"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Ghtop
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/patrickhoefler/ghtop/releases/download/v0.1.11/ghtop_0.1.11_linux_amd64.tar.gz"
      sha256 "865f77ca343cf9a76cb6d6a8ac7daec0868244cbcc29cf20e0f7759698b88385"

      def install
        bin.install "ghtop"
      end
    end
  end
end
