# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghtop < Formula
  desc "Get information about the most starred GitHub repos"
  homepage "https://github.com/patrickhoefler/ghtop"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickhoefler/ghtop/releases/download/v0.1.8/ghtop_0.1.8_darwin_amd64.tar.gz"
      sha256 "992f68852b97f781ed0db9715b7292669070f1cca4a5f826ad0813f12ac19bb1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/patrickhoefler/ghtop/releases/download/v0.1.8/ghtop_0.1.8_linux_amd64.tar.gz"
      sha256 "0ba428423cd085d1ba05ee42928b6507a39da79f83c75acbe4094fd3cee139f0"
    end
  end

  def install
    bin.install "ghtop"
  end
end
