# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghtop < Formula
  desc "Get information about the most starred GitHub repos"
  homepage "https://github.com/patrickhoefler/ghtop"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/patrickhoefler/ghtop/releases/download/v0.1.9/ghtop_0.1.9_darwin_amd64.tar.gz"
      sha256 "7eaa1563c601b267d04bc8a70be7008e0e11233e37af14f8ada4b9e15fd860a6"

      def install
        bin.install "ghtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/patrickhoefler/ghtop/releases/download/v0.1.9/ghtop_0.1.9_linux_amd64.tar.gz"
      sha256 "c59cb3699ec44775c3928dffe815a49188047c90ace7df79b66c52109321ae9d"

      def install
        bin.install "ghtop"
      end
    end
  end
end
